# Copy VS View

Copy es un nuevo array, y view es solo una vista del array original.

Copy posse la data y cualquier dato hecho a la copia que no afecta a la  array original, y cualquier cambio hecho al original no afecta a la copia.

View no posee la data o cualquier cambio hecho a la vista afectara la arreglo original, y cualquier cambio hecho al original afectara a la vista.

In [1]:
import numpy as np 

a = np.array ([1,2,3,4,5])
x = a.copy()

a[0]=42

print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
import numpy as np 

a = np.array ([1,2,3,4,5])
x = a.view()

a[0]=42
x[1]=54

print(a)
print(x)

[42 54  3  4  5]
[42 54  3  4  5]


# Verificar si un array posee su proia data

In [4]:
import numpy as np

a=np.array([1,2,3,4,5])

x=a.copy()
y=a.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
