# Interacion de arrays

In [2]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])

for x in a:
    print(x)

b=np.array([[1,2,3,4],[5,6,7,8]])

for x in b:
    print(x)

for x in b:
    for y in x:
        print(y)

c=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

for x in c:
    print(x)

for x in c:
    for y in x:
        for z in y:
            print(z)

for x in np.nditer(c):
    print(x)

1
2
3
4
5
6
7
8
[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


# Iteracion de arrays con nditer()
> Ayuda a simplificar la iteración de arrays con ciclos for identados.

In [3]:
import numpy as np

c=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

for x in np.nditer(c):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Iteracion con distintos tipos de datos
- Se puede emplear el argumento **op_dtypes** para especificar el tipo de dato para cambiarlos mientras se esta iterando.
- Numpy necesita un espacio para cambiar el tipo de dato llamado buffer por los cual se ingresa un argumento flags=["buffered"]

In [4]:
import numpy as np

a = np.array([1,2,3,4])

for x in np.nditer(a, flags=["buffered"], op_dtypes=["S"]):
    print(x)

b'1'
b'2'
b'3'
b'4'


# Iterar con saltos

In [6]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in np.nditer(a[:,:, ::2]):
    print(x)

1
3
4
6
7
9
10
12


# Enumerar iteracion

In [7]:
import numpy as np

a= np.array([[1,2,3],[4,5,6]])

for idx, x in np.ndenumerate(a):
    print(idx,x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
