# Juntar array

In [1]:
import numpy as np

a =np.array([1,2,3,4])
b =np.array([5,6,7,8])

x = np.concatenate((a,b))

print(x)

[1 2 3 4 5 6 7 8]


In [2]:
import numpy as np

a =np.array([[1,2],[3,4]])
b =np.array([[5,6],[7,8]])

# Une los array en base a las filas (axis=1)
x =np.concatenate((a,b),axis=1)
print(x)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Juntando array con la funcion stack

In [9]:
import numpy as np

a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])

x=np.stack((a,b), axis=1)
print(x)


# Estaquea los arrays a lo largo de una fila
y=np.hstack((a,b))
print(y)

#Estaque los arrays a lo largo de una columna
z=np.vstack((a,b))
print(z)

#
w=np.dstack((a,b))
print(w)


[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
