# Ordenar arrays

In [4]:
import numpy as np

x=np.array([5,3,2,7,4,1,6])
print(np.sort(x))

y=np.array(['manzana','banana', 'maranja'])
print(np.sort(y))

z=np.array([[4,5,3],[6,1,2]])
print(np.sort(z))


[1 2 3 4 5 6 7]
['banana' 'manzana' 'maranja']
[[3 4 5]
 [1 2 6]]
