# Numeros random en Numpy

In [10]:
import numpy as np
from numpy import random

x = random.randint(100)

print(x)

34


## Generar un float random entre 0 - 1

In [17]:
from numpy import random

x = random.rand()

print(x)

0.9459592888830859


## Generar array random

In [18]:
from numpy import random

# Array 1 - D random de enteros entre 0 - 100
x = random.randint(100, size = 5)
print(x)

# Array 1 -D random de float entre 0 - 1
y = random.rand(5)
print(y)

# Array 2 - D de float entre 0 - 1
z = random.rand(3,5)
print(z)



[76 66 25 26  6]
[0.08355766 0.56852274 0.65585647 0.159521   0.83456644]
[[0.48898308 0.19507586 0.29478977 0.05878886 0.13396304]
 [0.04967305 0.67462034 0.37486429 0.61692066 0.4055443 ]
 [0.23010677 0.78035156 0.25099146 0.53940658 0.10103485]]


## Generar random desde un array

In [24]:
from numpy import random

#Generar numero random desde un array
x = random.choice([3,5,7,9])
print(x)

#Generar array 2-D random desde un array
y = random.choice([3,5,7,9], size=(3,5))
print(y)

7
[[7 5 3 9 7]
 [5 7 3 9 9]
 [3 9 7 3 3]]
