# Distribucion de data random

In [2]:
from numpy import random

a = random.choice([3,5,7,9], p = [0.2,0.3,0.3,0.2], size = (100))
print(a)

b = random.choice([3,5,7,9], p = [0.2,0.3,0.3,0.2], size = (4,5))
print(b)

[7 5 5 5 7 5 3 7 5 5 5 7 9 5 9 9 7 9 3 7 7 9 3 3 5 7 7 7 9 3 3 5 9 3 9 9 7
 3 3 3 7 7 5 5 5 7 3 3 3 3 3 5 5 9 3 7 5 7 7 3 9 5 5 5 7 9 3 3 7 7 9 5 7 3
 5 7 7 7 9 5 9 3 5 5 3 5 9 3 5 5 9 3 9 7 9 3 5 9 5 7]
[[9 3 7 7 5]
 [9 3 3 7 5]
 [5 3 5 3 5]
 [9 7 7 9 3]]
