# Permutacion randon de elementos
> La permutacion hace referencia a la posicion de los elemntos en el arreglo

In [3]:
from numpy import random
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])

# Cambia la posicion de los elementos de un arreglo, sin modificar el arreglo original
x = random.permutation(a)
print(x)

print(a)

# Cambiar la posicion de los elementos del array
random.shuffle(a)
print(a)

# 


[4 6 7 9 1 3 5 2 8]
None
[1 2 3 4 5 6 7 8 9]
[1 3 7 5 4 9 6 2 8]
