# Filtar arrays

In [2]:
import numpy as np

a= np.array([1,2,3,4,5,6])

#Arreglo de filtro
x = [True,False,True,False,False,True]

nx = a[x]

print(nx)


[1 3 6]


# Crear un array filtro

In [4]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])

filter_arr = []

for x in a:
    # Para cada elemento par, establece valor True
    if x % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

na = a[filter_arr]

print(filter_arr)
print(na)


[False, True, False, True, False, True, False, True]
[2 4 6 8]


In [5]:
import numpy as np

a = np.array([1,2,3,4,5,6])

filter_a= a % 2 != 0

na = a[filter_a]

print(filter_a)
print(na)

[ True False  True False  True False]
[1 3 5]
